{"name": "test_fixture_scope_function01", "status": "failed", "statusDetails": {"message": "AssertionError: assert 53 > 100", "trace": "random_num = 53\n\n    def test_fixture_scope_function01(random_num):\n        print(f'random_num: {random_num}')\n>       assert random_num > 100\nE       assert 53 > 100\n\ntest_02_fixture.py:55: AssertionError"}, "start": 1627038104456, "stop": 1627038104457, "uuid": "854a04cf-f87c-426b-a2f9-a640b1333813", "historyId": "28ba27a727214e9f136753a0e7ec0861", "testCaseId": "d6107e9d64e1b9ad873f850e6cd7c510", "fullName": "test_02_fixture#test_fixture_scope_function01", "labels": [{"name": "suite", "value": "test_02_fixture"}, {"name": "host", "value": "JULIZHOU-6JV5P"}, {"name": "thread", "value": "18748-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_02_fixture"}]}