{"name": "test_fixture_scope_function01", "status": "failed", "statusDetails": {"message": "AssertionError: assert 55 > 100", "trace": "random_num = 55\n\n    def test_fixture_scope_function01(random_num):\n        print(f'random_num: {random_num}')\n>       assert random_num > 100\nE       assert 55 > 100\n\ntest_02_fixture.py:55: AssertionError"}, "start": 1627038694201, "stop": 1627038694202, "uuid": "4d1f5475-97b9-4b7c-bdb7-8e991c828205", "historyId": "28ba27a727214e9f136753a0e7ec0861", "testCaseId": "d6107e9d64e1b9ad873f850e6cd7c510", "fullName": "test_02_fixture#test_fixture_scope_function01", "labels": [{"name": "suite", "value": "test_02_fixture"}, {"name": "host", "value": "JULIZHOU-6JV5P"}, {"name": "thread", "value": "19824-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_02_fixture"}]}