{"name": "test_fixture_scope_function02", "status": "failed", "statusDetails": {"message": "AssertionError: assert 33 > 100", "trace": "random_num = 33\n\n    def test_fixture_scope_function02(random_num):\n        print(f'random_num: {random_num}')\n>       assert random_num > 100\nE       assert 33 > 100\n\ntest_02_fixture.py:60: AssertionError"}, "start": 1627038694233, "stop": 1627038694234, "uuid": "558b8b85-dc47-4da1-b04d-4cfcc8af5963", "historyId": "40cc6378bf49404693017b0e13f6ddf6", "testCaseId": "c070a04923b6c70944d2180706a90f72", "fullName": "test_02_fixture#test_fixture_scope_function02", "labels": [{"name": "suite", "value": "test_02_fixture"}, {"name": "host", "value": "JULIZHOU-6JV5P"}, {"name": "thread", "value": "19824-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_02_fixture"}]}