{"name": "test_zero_division", "status": "passed", "start": 1627037543450, "stop": 1627037543450, "uuid": "d19312ef-5902-4dcb-a15a-ccb6633b8f55", "historyId": "a14aec89c78ce6de10541e72661fa99b", "testCaseId": "c3a200565686ede67a35e0acea377cae", "fullName": "test_01_assert_for_allure.TestAllure#test_zero_division", "labels": [{"name": "story", "value": "assert"}, {"name": "suite", "value": "test_01_assert_for_allure"}, {"name": "subSuite", "value": "TestAllure"}, {"name": "host", "value": "JULIZHOU-6JV5P"}, {"name": "thread", "value": "4280-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_01_assert_for_allure"}], "links": [{"type": "test_case", "url": "case url", "name": "# 3. 异常断言，使用pytest.raises作为上下文管理器"}]}