{"name": "test_02", "status": "broken", "statusDetails": {"message": "TypeError: 传入参数非整数", "trace": "self = <test_demo.test_03_mark_for_allure.TestMark object at 0x00000287F82CDCC8>\n\n    @allure.story(\"story: story in class\")\n    @pytest.mark.xfail(raises=ValueError)\n    def test_02(self):\n        if isinstance('1234', int) is not True:\n>           raise TypeError(\"传入参数非整数\")\nE           TypeError: 传入参数非整数\n\ntest_03_mark_for_allure.py:66: TypeError"}, "start": 1627038117202, "stop": 1627038117202, "uuid": "ecba9c9d-2e16-418d-9f5c-d023f3b8cac2", "historyId": "361c21a93eba7f5aaadba821289727d2", "testCaseId": "a9f43ef1ecb8e46aba18cd2917bb4f9d", "fullName": "test_03_mark_for_allure.TestMark#test_02", "labels": [{"name": "story", "value": "story: story in class"}, {"name": "feature", "value": "feature: test_03_mark, feature mark at class level"}, {"name": "tag", "value": "@pytest.mark.xfail(raises=<class 'ValueError'>)"}, {"name": "suite", "value": "test_03_mark_for_allure"}, {"name": "subSuite", "value": "TestMark"}, {"name": "host", "value": "JULIZHOU-6JV5P"}, {"name": "thread", "value": "18748-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_03_mark_for_allure"}]}