{"name": "test_recursion_depth", "status": "passed", "start": 1627037543458, "stop": 1627037543459, "uuid": "34414d5b-cfce-4318-be43-5ed78fca699a", "historyId": "c342a6a00b7d70faff35ceb6aae7cb1c", "testCaseId": "981aeaa12154ed8e1639facf5538e79b", "fullName": "test_01_assert_for_allure.TestAllure#test_recursion_depth", "labels": [{"name": "story", "value": "assert"}, {"name": "suite", "value": "test_01_assert_for_allure"}, {"name": "subSuite", "value": "TestAllure"}, {"name": "host", "value": "JULIZHOU-6JV5P"}, {"name": "thread", "value": "4280-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_01_assert_for_allure"}], "links": [{"type": "test_case", "url": "case url", "name": "# 3. 异常断言，使用pytest.raises作为上下文管理器"}]}